info:
  description: "This is the API documentation for the Hacker News we created"
  version: 0.0.1
  title: "Hacker News - G11D"
swagger: '2.0'
produces:
  - application/xml
  - application/json
  - application/octet-stream
  - text/plain
host: localhost:3000 
basePath: "/api/v1"
tags:
  - name: contributions
    description: "All comtributions REST calls"
schemes:
- "http"
paths:
  /contributions:
    get:
      tags:
      - contributions
      summary: "Return all the contributions. They can be filtered"
      operationId: getAllContributions
      produces:
      - application/json
      parameters:
      - in: query
        name: type
        required: false
        type: string
        enum: [ask, new]
      responses:
        204:
          description: "No contributions found"
        400:
          description: "Invalid query"
      security:
      - api_key: []

securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header